// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import type { OptionType } from '$lib/components/Filters/Base/Base.svelte';

export const publishLanguages: OptionType[] = [
	{ value: 'lang_ar', label: 'Arabic' },
	{ value: 'lang_hy', label: 'Armenian' },
	{ value: 'lang_be', label: 'Belarusian' },
	{ value: 'lang_bg', label: 'Bulgarian' },
	{ value: 'lang_ca', label: 'Catalan' },
	{ value: 'lang_zh-cn', label: 'Chinese Simplified' },
	{ value: 'lang_zh-tw', label: 'Chinese Traditional' },
	{ value: 'lang_hr', label: 'Croatian' },
	{ value: 'lang_cs', label: 'Czech' },
	{ value: 'lang_da', label: 'Danish' },
	{ value: 'lang_nl', label: 'Dutch' },
	{ value: 'lang_en', label: 'English' },
	{ value: 'lang_eo', label: 'Esperanto' },
	{ value: 'lang_et', label: 'Estonian' },
	{ value: 'lang_tl', label: 'Filipino' },
	{ value: 'lang_fi', label: 'Finnish' },
	{ value: 'lang_fr', label: 'French' },
	{ value: 'lang_de', label: 'German' },
	{ value: 'lang_el', label: 'Greek' },
	{ value: 'lang_iw', label: 'Hebrew' },
	{ value: 'lang_hu', label: 'Hungarian' },
	{ value: 'lang_is', label: 'Icelandic' },
	{ value: 'lang_id', label: 'Indonesian' },
	{ value: 'lang_it', label: 'Italian' },
	{ value: 'lang_ja', label: 'Japanese' },
	{ value: 'lang_ko', label: 'Korean' },
	{ value: 'lang_lv', label: 'Latvian' },
	{ value: 'lang_lt', label: 'Lithuanian' },
	{ value: 'lang_no', label: 'Norwegian' },
	{ value: 'lang_fa', label: 'Persian' },
	{ value: 'lang_pl', label: 'Polish' },
	{ value: 'lang_pt', label: 'Portuguese' },
	{ value: 'lang_ro', label: 'Romanian' },
	{ value: 'lang_ru', label: 'Russian' },
	{ value: 'lang_sr', label: 'Serbian' },
	{ value: 'lang_sk', label: 'Slovak' },
	{ value: 'lang_sl', label: 'Slovenian' },
	{ value: 'lang_es', label: 'Spanish' },
	{ value: 'lang_sv', label: 'Swedish' },
	{ value: 'lang_th', label: 'Thai' },
	{ value: 'lang_tr', label: 'Turkish' },
	{ value: 'lang_uk', label: 'Ukrainian' },
	{ value: 'lang_vi', label: 'Vietnamese' }
];
